from .auth_service import AuthService
from .class_service import ClassService
from .course_service import CourseService
from .dashboard_service import DashboardService
from .evaluation_service import EvaluationService
from .file_storage_service import FileStorageService
from .homework_service import HomeworkService
from .openai_evaluation_service import OpenAIEvaluationService
from .report_service import ReportService
from .review_service import ReviewService
from .task_service import TaskService
from .user_service import UserService
